{
	"success": true,
	"vo": {
		"children": [{
			"children": [{
				"key": "62835",
				"value": "用户管理",
				"sortIndex": 9100,
				"parentKey": "62834",
				"isLeaf": false,
				"checkboxState": 2,
				"data": {
					"id": 62835,
					"lockVersion": 0,
					"name": "用户管理",
					"type": "MENU",
					"url": "#pjs/UserInfo",
					"parentId": 62834,
					"parentPath": "61352|62834|62835",
					"sortIndex": 9100,
					"locked": false
				},
				"leaf": false
			}, {
				"key": "62836",
				"value": "角色管理",
				"sortIndex": 9200,
				"parentKey": "62834",
				"isLeaf": false,
				"checkboxState": 2,
				"data": {
					"id": 62836,
					"lockVersion": 0,
					"name": "角色管理",
					"type": "MENU",
					"url": "#pjs/RoleInfo",
					"parentId": 62834,
					"parentPath": "61352|62834|62836",
					"sortIndex": 9200,
					"locked": false
				},
				"leaf": false
			}],
			"key": "62834",
			"value": "系统管理",
			"sortIndex": 9000,
			"parentKey": "61352",
			"isLeaf": false,
			"checkboxState": 2,
			"data": {
				"id": 62834,
				"lockVersion": 0,
				"name": "系统管理",
				"type": "MENU_DIR",
				"parentId": 61352,
				"parentPath": "61352|62834",
				"sortIndex": 9000,
				"locked": false
			},
			"leaf": false
		}, {
			"children": [{
				"children": [{
					"key": "64614",
					"value": "添加",
					"sortIndex": 11001,
					"parentKey": "61319",
					"isLeaf": false,
					"checkboxState": 2,
					"data": {
						"id": 64614,
						"lockVersion": 0,
						"name": "添加",
						"type": "PERMISSION",
						"parentId": 61319,
						"permission": "hub:add",
						"sortIndex": 11001,
						"locked": false
					},
					"leaf": false
				}, {
					"key": "64615",
					"value": "编辑",
					"sortIndex": 11002,
					"parentKey": "61319",
					"isLeaf": false,
					"checkboxState": 2,
					"data": {
						"id": 64615,
						"lockVersion": 0,
						"name": "编辑",
						"type": "PERMISSION",
						"parentId": 61319,
						"permission": "hub:edit",
						"sortIndex": 11002,
						"locked": false
					},
					"leaf": false
				}, {
					"key": "64616",
					"value": "删除",
					"sortIndex": 11003,
					"parentKey": "61319",
					"isLeaf": false,
					"checkboxState": 2,
					"data": {
						"id": 64616,
						"lockVersion": 0,
						"name": "删除",
						"type": "PERMISSION",
						"parentId": 61319,
						"permission": "hub:delete",
						"sortIndex": 11003,
						"locked": false
					},
					"leaf": false
				}, {
					"key": "64617",
					"value": "禁用",
					"sortIndex": 11004,
					"parentKey": "61319",
					"isLeaf": false,
					"checkboxState": 2,
					"data": {
						"id": 64617,
						"lockVersion": 0,
						"name": "禁用",
						"type": "PERMISSION",
						"parentId": 61319,
						"permission": "hub:lock",
						"sortIndex": 11004,
						"locked": false
					},
					"leaf": false
				}, {
					"key": "64618",
					"value": "启用",
					"sortIndex": 11005,
					"parentKey": "61319",
					"isLeaf": false,
					"checkboxState": 2,
					"data": {
						"id": 64618,
						"lockVersion": 0,
						"name": "启用",
						"type": "PERMISSION",
						"parentId": 61319,
						"permission": "hub:unlock",
						"sortIndex": 11005,
						"locked": false
					},
					"leaf": false
				}],
				"key": "61319",
				"value": "分拨信息",
				"sortIndex": 11000,
				"parentKey": "61315",
				"isLeaf": false,
				"checkboxState": 2,
				"data": {
					"id": 61319,
					"lockVersion": 0,
					"name": "分拨信息",
					"type": "MENU",
					"url": "#pjs/HubInfo",
					"parentId": 61315,
					"parentPath": "61352|61315|61319",
					"sortIndex": 11000,
					"locked": false
				},
				"leaf": false
			}, {
				"children": [{
					"key": "64619",
					"value": "添加",
					"sortIndex": 12001,
					"parentKey": "61320",
					"isLeaf": false,
					"checkboxState": 2,
					"data": {
						"id": 64619,
						"lockVersion": 0,
						"name": "添加",
						"type": "PERMISSION",
						"parentId": 61320,
						"permission": "os:add",
						"sortIndex": 12001,
						"locked": false
					},
					"leaf": false
				}, {
					"key": "64620",
					"value": "编辑",
					"sortIndex": 12002,
					"parentKey": "61320",
					"isLeaf": false,
					"checkboxState": 2,
					"data": {
						"id": 64620,
						"lockVersion": 0,
						"name": "编辑",
						"type": "PERMISSION",
						"parentId": 61320,
						"permission": "os:edit",
						"sortIndex": 12002,
						"locked": false
					},
					"leaf": false
				}, {
					"key": "64621",
					"value": "删除",
					"sortIndex": 12003,
					"parentKey": "61320",
					"isLeaf": false,
					"checkboxState": 2,
					"data": {
						"id": 64621,
						"lockVersion": 0,
						"name": "删除",
						"type": "PERMISSION",
						"parentId": 61320,
						"permission": "os:delete",
						"sortIndex": 12003,
						"locked": false
					},
					"leaf": false
				}, {
					"key": "64622",
					"value": "禁用",
					"sortIndex": 12004,
					"parentKey": "61320",
					"isLeaf": false,
					"checkboxState": 2,
					"data": {
						"id": 64622,
						"lockVersion": 0,
						"name": "禁用",
						"type": "PERMISSION",
						"parentId": 61320,
						"permission": "os:lock",
						"sortIndex": 12004,
						"locked": false
					},
					"leaf": false
				}, {
					"key": "64623",
					"value": "启用",
					"sortIndex": 12005,
					"parentKey": "61320",
					"isLeaf": false,
					"checkboxState": 2,
					"data": {
						"id": 64623,
						"lockVersion": 0,
						"name": "启用",
						"type": "PERMISSION",
						"parentId": 61320,
						"permission": "os:unlock",
						"sortIndex": 12005,
						"locked": false
					},
					"leaf": false
				}],
				"key": "61320",
				"value": "操作点信息",
				"sortIndex": 12000,
				"parentKey": "61315",
				"isLeaf": false,
				"checkboxState": 2,
				"data": {
					"id": 61320,
					"lockVersion": 0,
					"name": "操作点信息",
					"type": "MENU",
					"url": "#pjs/OSInfo",
					"parentId": 61315,
					"parentPath": "61352|61315|61320",
					"sortIndex": 12000,
					"locked": false
				},
				"leaf": false
			}, {
				"children": [{
					"key": "64686",
					"value": "添加",
					"sortIndex": 11001,
					"parentKey": "64685",
					"isLeaf": false,
					"checkboxState": 2,
					"data": {
						"id": 64686,
						"lockVersion": 0,
						"name": "添加",
						"type": "PERMISSION",
						"parentId": 64685,
						"permission": "laneSeg:add",
						"sortIndex": 11001,
						"locked": false
					},
					"leaf": false
				}, {
					"key": "64687",
					"value": "编辑",
					"sortIndex": 11002,
					"parentKey": "64685",
					"isLeaf": false,
					"checkboxState": 2,
					"data": {
						"id": 64687,
						"lockVersion": 0,
						"name": "编辑",
						"type": "PERMISSION",
						"parentId": 64685,
						"permission": "laneSeg:edit",
						"sortIndex": 11002,
						"locked": false
					},
					"leaf": false
				}, {
					"key": "64688",
					"value": "审核",
					"sortIndex": 11003,
					"parentKey": "64685",
					"isLeaf": false,
					"checkboxState": 2,
					"data": {
						"id": 64688,
						"lockVersion": 0,
						"name": "审核",
						"type": "PERMISSION",
						"parentId": 64685,
						"permission": "laneSeg:audit",
						"sortIndex": 11003,
						"locked": false
					},
					"leaf": false
				}, {
					"key": "64689",
					"value": "禁用",
					"sortIndex": 11004,
					"parentKey": "64685",
					"isLeaf": false,
					"checkboxState": 2,
					"data": {
						"id": 64689,
						"lockVersion": 0,
						"name": "禁用",
						"type": "PERMISSION",
						"parentId": 64685,
						"permission": "laneSeg:lock",
						"sortIndex": 11004,
						"locked": false
					},
					"leaf": false
				}, {
					"key": "64690",
					"value": "启用",
					"sortIndex": 11005,
					"parentKey": "64685",
					"isLeaf": false,
					"checkboxState": 2,
					"data": {
						"id": 64690,
						"lockVersion": 0,
						"name": "启用",
						"type": "PERMISSION",
						"parentId": 64685,
						"permission": "laneSeg:unlock",
						"sortIndex": 11005,
						"locked": false
					},
					"leaf": false
				}, {
					"key": "64691",
					"value": "导出",
					"sortIndex": 11006,
					"parentKey": "64685",
					"isLeaf": false,
					"checkboxState": 2,
					"data": {
						"id": 64691,
						"lockVersion": 0,
						"name": "导出",
						"type": "PERMISSION",
						"parentId": 64685,
						"permission": "laneSeg:export",
						"sortIndex": 11006,
						"locked": false
					},
					"leaf": false
				}, {
					"key": "64692",
					"value": "模板下载",
					"sortIndex": 11007,
					"parentKey": "64685",
					"isLeaf": false,
					"checkboxState": 2,
					"data": {
						"id": 64692,
						"lockVersion": 0,
						"name": "模板下载",
						"type": "PERMISSION",
						"parentId": 64685,
						"permission": "laneSeg:importTempDownload",
						"sortIndex": 11007,
						"locked": false
					},
					"leaf": false
				}, {
					"key": "64705",
					"value": "历史记录",
					"sortIndex": 11007,
					"parentKey": "64685",
					"isLeaf": false,
					"checkboxState": 2,
					"data": {
						"id": 64705,
						"lockVersion": 0,
						"name": "历史记录",
						"type": "PERMISSION",
						"parentId": 64685,
						"permission": "laneSeg:history",
						"sortIndex": 11007,
						"locked": false
					},
					"leaf": false
				}, {
					"key": "64693",
					"value": "导入",
					"sortIndex": 11008,
					"parentKey": "64685",
					"isLeaf": false,
					"checkboxState": 2,
					"data": {
						"id": 64693,
						"lockVersion": 0,
						"name": "导入",
						"type": "PERMISSION",
						"parentId": 64685,
						"permission": "laneSeg:import",
						"sortIndex": 11008,
						"locked": false
					},
					"leaf": false
				}],
				"key": "64685",
				"value": "路段管理",
				"sortIndex": 21500,
				"parentKey": "61315",
				"isLeaf": false,
				"checkboxState": 2,
				"data": {
					"id": 64685,
					"lockVersion": 0,
					"name": "路段管理",
					"type": "MENU",
					"url": "#pjs/LaneSegInfo",
					"parentId": 61315,
					"parentPath": "61352|61315|64685",
					"sortIndex": 21500,
					"locked": false
				},
				"leaf": false
			}],
			"key": "61315",
			"value": "基础信息",
			"sortIndex": 10000,
			"parentKey": "61352",
			"isLeaf": false,
			"checkboxState": 2,
			"data": {
				"id": 61315,
				"lockVersion": 0,
				"name": "基础信息",
				"type": "MENU_DIR",
				"parentId": 61352,
				"parentPath": "61352|61315",
				"sortIndex": 10000,
				"locked": false
			},
			"leaf": false
		}, {
			"children": [{
				"children": [{
					"key": "62837",
					"value": "添加版本",
					"sortIndex": 20001,
					"parentKey": "61324",
					"isLeaf": false,
					"checkboxState": 2,
					"data": {
						"id": 62837,
						"lockVersion": 0,
						"name": "添加版本",
						"type": "PERMISSION",
						"parentId": 61324,
						"permission": "version:add",
						"sortIndex": 20001,
						"locked": false
					},
					"leaf": false
				}, {
					"key": "62838",
					"value": "编辑版本",
					"sortIndex": 20002,
					"parentKey": "61324",
					"isLeaf": false,
					"checkboxState": 2,
					"data": {
						"id": 62838,
						"lockVersion": 0,
						"name": "编辑版本",
						"type": "PERMISSION",
						"parentId": 61324,
						"permission": "version:edit",
						"sortIndex": 20002,
						"locked": false
					},
					"leaf": false
				}, {
					"key": "62840",
					"value": "检测版本",
					"sortIndex": 20003,
					"parentKey": "61324",
					"isLeaf": false,
					"checkboxState": 2,
					"data": {
						"id": 62840,
						"lockVersion": 0,
						"name": "检测版本",
						"type": "PERMISSION",
						"parentId": 61324,
						"permission": "version:inspect",
						"sortIndex": 20003,
						"locked": false
					},
					"leaf": false
				}, {
					"key": "62839",
					"value": "发布版本",
					"sortIndex": 20004,
					"parentKey": "61324",
					"isLeaf": false,
					"checkboxState": 2,
					"data": {
						"id": 62839,
						"lockVersion": 0,
						"name": "发布版本",
						"type": "PERMISSION",
						"parentId": 61324,
						"permission": "version:publish",
						"sortIndex": 20004,
						"locked": false
					},
					"leaf": false
				}],
				"key": "61324",
				"value": "版本管理",
				"sortIndex": 20000,
				"parentKey": "61316",
				"isLeaf": false,
				"checkboxState": 2,
				"data": {
					"id": 61324,
					"lockVersion": 0,
					"name": "版本管理",
					"type": "MENU",
					"url": "#pjs/VersionInfo",
					"parentId": 61316,
					"parentPath": "61352|61316|61324",
					"sortIndex": 20000,
					"locked": false
				},
				"leaf": false
			}, {
				"children": [{
					"children": [{
						"key": "68481",
						"value": "添加批次",
						"sortIndex": 21001,
						"parentKey": "61330",
						"isLeaf": false,
						"checkboxState": 2,
						"data": {
							"id": 68481,
							"lockVersion": 0,
							"name": "添加批次",
							"type": "PERMISSION",
							"parentId": 61330,
							"permission": "transitBatch:add",
							"sortIndex": 21001,
							"locked": false
						},
						"leaf": false
					}, {
						"key": "68482",
						"value": "编辑批次",
						"sortIndex": 21002,
						"parentKey": "61330",
						"isLeaf": false,
						"checkboxState": 2,
						"data": {
							"id": 68482,
							"lockVersion": 0,
							"name": "编辑批次",
							"type": "PERMISSION",
							"parentId": 61330,
							"permission": "transitBatch:edit",
							"sortIndex": 21002,
							"locked": false
						},
						"leaf": false
					}, {
						"key": "68483",
						"value": "删除批次",
						"sortIndex": 21003,
						"parentKey": "61330",
						"isLeaf": false,
						"checkboxState": 2,
						"data": {
							"id": 68483,
							"lockVersion": 0,
							"name": "删除批次",
							"type": "PERMISSION",
							"parentId": 61330,
							"permission": "transitBatch:delete",
							"sortIndex": 21003,
							"locked": false
						},
						"leaf": false
					}, {
						"key": "68484",
						"value": "添加目的分拨",
						"sortIndex": 21004,
						"parentKey": "61330",
						"isLeaf": false,
						"checkboxState": 2,
						"data": {
							"id": 68484,
							"lockVersion": 0,
							"name": "添加目的分拨",
							"type": "PERMISSION",
							"parentId": 61330,
							"permission": "nextHub:add",
							"sortIndex": 21004,
							"locked": false
						},
						"leaf": false
					}, {
						"key": "68485",
						"value": "自动匹配下一站",
						"sortIndex": 21005,
						"parentKey": "61330",
						"isLeaf": false,
						"checkboxState": 2,
						"data": {
							"id": 68485,
							"lockVersion": 0,
							"name": "自动匹配下一站",
							"type": "PERMISSION",
							"parentId": 61330,
							"permission": "nextHub:match",
							"sortIndex": 21005,
							"locked": false
						},
						"leaf": false
					}, {
						"key": "68486",
						"value": "初始化出港路由",
						"sortIndex": 21006,
						"parentKey": "61330",
						"isLeaf": false,
						"checkboxState": 2,
						"data": {
							"id": 68486,
							"lockVersion": 0,
							"name": "初始化出港路由",
							"type": "PERMISSION",
							"parentId": 61330,
							"permission": "nextHub:init",
							"sortIndex": 21006,
							"locked": false
						},
						"leaf": false
					}, {
						"key": "68487",
						"value": "调整出港路由",
						"sortIndex": 21007,
						"parentKey": "61330",
						"isLeaf": false,
						"checkboxState": 2,
						"data": {
							"id": 68487,
							"lockVersion": 0,
							"name": "调整出港路由",
							"type": "PERMISSION",
							"parentId": 61330,
							"permission": "nextHub:updateBatch",
							"sortIndex": 21007,
							"locked": false
						},
						"leaf": false
					}, {
						"key": "68480",
						"value": "调整备用路由",
						"sortIndex": 21008,
						"parentKey": "61330",
						"isLeaf": false,
						"checkboxState": 2,
						"data": {
							"id": 68480,
							"lockVersion": 0,
							"name": "调整备用路由",
							"type": "PERMISSION",
							"parentId": 61330,
							"permission": "nextHub:updateBatchBak",
							"sortIndex": 21008,
							"locked": false
						},
						"leaf": false
					}],
					"key": "61330",
					"value": "非接入型分拨批次配置",
					"sortIndex": 21100,
					"parentKey": "61322",
					"isLeaf": false,
					"checkboxState": 2,
					"data": {
						"id": 61330,
						"lockVersion": 0,
						"name": "非接入型分拨批次配置",
						"type": "MENU",
						"url": "#pjs/TransitRouteInfo",
						"parentId": 61322,
						"parentPath": "61352|61316|61322|61330",
						"sortIndex": 21100,
						"locked": false
					},
					"leaf": false
				}, {
					"children": [{
						"key": "64624",
						"value": "调整路由",
						"sortIndex": 21201,
						"parentKey": "62833",
						"isLeaf": false,
						"checkboxState": 2,
						"data": {
							"id": 64624,
							"lockVersion": 0,
							"name": "调整路由",
							"type": "PERMISSION",
							"parentId": 62833,
							"permission": "route:adjust",
							"sortIndex": 21201,
							"locked": false
						},
						"leaf": false
					}],
					"key": "62833",
					"value": "分拨路由调整",
					"sortIndex": 21200,
					"parentKey": "61322",
					"isLeaf": false,
					"checkboxState": 2,
					"data": {
						"id": 62833,
						"lockVersion": 0,
						"name": "分拨路由调整",
						"type": "MENU",
						"url": "#pjs/TransitRouteAdjustInfo",
						"parentId": 61322,
						"parentPath": "61352|61316|61322|62833",
						"sortIndex": 21200,
						"locked": false
					},
					"leaf": false
				}, {
					"children": [{
						"key": "64625",
						"value": "添加",
						"sortIndex": 21301,
						"parentKey": "61332",
						"isLeaf": false,
						"checkboxState": 2,
						"data": {
							"id": 64625,
							"lockVersion": 0,
							"name": "添加",
							"type": "PERMISSION",
							"parentId": 61332,
							"permission": "joinBatch:add",
							"sortIndex": 21301,
							"locked": false
						},
						"leaf": false
					}, {
						"key": "64626",
						"value": "编辑",
						"sortIndex": 21302,
						"parentKey": "61332",
						"isLeaf": false,
						"checkboxState": 2,
						"data": {
							"id": 64626,
							"lockVersion": 0,
							"name": "编辑",
							"type": "PERMISSION",
							"parentId": 61332,
							"permission": "joinBatch:edit",
							"sortIndex": 21302,
							"locked": false
						},
						"leaf": false
					}, {
						"key": "64627",
						"value": "删除",
						"sortIndex": 21303,
						"parentKey": "61332",
						"isLeaf": false,
						"checkboxState": 2,
						"data": {
							"id": 64627,
							"lockVersion": 0,
							"name": "删除",
							"type": "PERMISSION",
							"parentId": 61332,
							"permission": "joinBatch:delete",
							"sortIndex": 21303,
							"locked": false
						},
						"leaf": false
					}, {
						"key": "64645",
						"value": "更新接入型分拨配载区域",
						"sortIndex": 21303,
						"parentKey": "61332",
						"isLeaf": false,
						"checkboxState": 2,
						"data": {
							"id": 64645,
							"lockVersion": 0,
							"name": "更新接入型分拨配载区域",
							"type": "PERMISSION",
							"parentId": 61332,
							"permission": "joinBatch:complete",
							"sortIndex": 21303,
							"locked": false
						},
						"leaf": false
					}],
					"key": "61332",
					"value": "接入型分拨批次配置",
					"sortIndex": 21300,
					"parentKey": "61322",
					"isLeaf": false,
					"checkboxState": 2,
					"data": {
						"id": 61332,
						"lockVersion": 0,
						"name": "接入型分拨批次配置",
						"type": "MENU",
						"url": "#pjs/BexJoinInBatchConfigInfo",
						"parentId": 61322,
						"parentPath": "61352|61316|61322|61332",
						"sortIndex": 21300,
						"locked": false
					},
					"leaf": false
				}, {
					"children": [{
						"key": "64628",
						"value": "添加",
						"sortIndex": 21401,
						"parentKey": "61333",
						"isLeaf": false,
						"checkboxState": 2,
						"data": {
							"id": 64628,
							"lockVersion": 0,
							"name": "添加",
							"type": "PERMISSION",
							"parentId": 61333,
							"permission": "waveConfig:add",
							"sortIndex": 21401,
							"locked": false
						},
						"leaf": false
					}, {
						"key": "64629",
						"value": "编辑",
						"sortIndex": 21402,
						"parentKey": "61333",
						"isLeaf": false,
						"checkboxState": 2,
						"data": {
							"id": 64629,
							"lockVersion": 0,
							"name": "编辑",
							"type": "PERMISSION",
							"parentId": 61333,
							"permission": "waveConfig:edit",
							"sortIndex": 21402,
							"locked": false
						},
						"leaf": false
					}, {
						"key": "64630",
						"value": "删除",
						"sortIndex": 21403,
						"parentKey": "61333",
						"isLeaf": false,
						"checkboxState": 2,
						"data": {
							"id": 64630,
							"lockVersion": 0,
							"name": "删除",
							"type": "PERMISSION",
							"parentId": 61333,
							"permission": "waveConfig:delete",
							"sortIndex": 21403,
							"locked": false
						},
						"leaf": false
					}, {
						"key": "64642",
						"value": "未参加频次的站点",
						"sortIndex": 21404,
						"parentKey": "61333",
						"isLeaf": false,
						"checkboxState": 2,
						"data": {
							"id": 64642,
							"lockVersion": 0,
							"name": "未参加频次的站点",
							"type": "PERMISSION",
							"parentId": 61333,
							"permission": "scanSignAging:notPctpWaveSite",
							"sortIndex": 21404,
							"locked": false
						},
						"leaf": false
					}],
					"key": "61333",
					"value": "频次配置",
					"sortIndex": 21400,
					"parentKey": "61322",
					"isLeaf": false,
					"checkboxState": 2,
					"data": {
						"id": 61333,
						"lockVersion": 0,
						"name": "频次配置",
						"type": "MENU",
						"url": "#pjs/BexCalendarWaveConfigInfo",
						"parentId": 61322,
						"parentPath": "61352|61316|61322|61333",
						"sortIndex": 21400,
						"locked": false
					},
					"leaf": false
				}, {
					"children": [{
						"key": "64631",
						"value": "添加",
						"sortIndex": 21501,
						"parentKey": "61323",
						"isLeaf": false,
						"checkboxState": 2,
						"data": {
							"id": 64631,
							"lockVersion": 0,
							"name": "添加",
							"type": "PERMISSION",
							"parentId": 61323,
							"permission": "schedule:add",
							"sortIndex": 21501,
							"locked": false
						},
						"leaf": false
					}, {
						"key": "64632",
						"value": "编辑",
						"sortIndex": 21502,
						"parentKey": "61323",
						"isLeaf": false,
						"checkboxState": 2,
						"data": {
							"id": 64632,
							"lockVersion": 0,
							"name": "编辑",
							"type": "PERMISSION",
							"parentId": 61323,
							"permission": "schedule:edit",
							"sortIndex": 21502,
							"locked": false
						},
						"leaf": false
					}, {
						"key": "64633",
						"value": "删除",
						"sortIndex": 21503,
						"parentKey": "61323",
						"isLeaf": false,
						"checkboxState": 2,
						"data": {
							"id": 64633,
							"lockVersion": 0,
							"name": "删除",
							"type": "PERMISSION",
							"parentId": 61323,
							"permission": "schedule:delete",
							"sortIndex": 21503,
							"locked": false
						},
						"leaf": false
					}, {
						"key": "64634",
						"value": "关闭",
						"sortIndex": 21504,
						"parentKey": "61323",
						"isLeaf": false,
						"checkboxState": 2,
						"data": {
							"id": 64634,
							"lockVersion": 0,
							"name": "关闭",
							"type": "PERMISSION",
							"parentId": 61323,
							"permission": "schedule:lock",
							"sortIndex": 21504,
							"locked": false
						},
						"leaf": false
					}, {
						"key": "64635",
						"value": "启用",
						"sortIndex": 21505,
						"parentKey": "61323",
						"isLeaf": false,
						"checkboxState": 2,
						"data": {
							"id": 64635,
							"lockVersion": 0,
							"name": "启用",
							"type": "PERMISSION",
							"parentId": 61323,
							"permission": "schedule:unlock",
							"sortIndex": 21505,
							"locked": false
						},
						"leaf": false
					}, {
						"key": "64636",
						"value": "批量修改到发批次",
						"sortIndex": 21506,
						"parentKey": "61323",
						"isLeaf": false,
						"checkboxState": 2,
						"data": {
							"id": 64636,
							"lockVersion": 0,
							"name": "批量修改到发批次",
							"type": "PERMISSION",
							"parentId": 61323,
							"permission": "schedule:modifyDepAndArrBatch",
							"sortIndex": 21506,
							"locked": false
						},
						"leaf": false
					}, {
						"key": "64644",
						"value": "查看",
						"sortIndex": 21507,
						"parentKey": "61323",
						"isLeaf": false,
						"checkboxState": 2,
						"data": {
							"id": 64644,
							"lockVersion": 0,
							"name": "查看",
							"type": "PERMISSION",
							"parentId": 61323,
							"permission": "schedule:query",
							"sortIndex": 21507,
							"locked": false
						},
						"leaf": false
					}, {
						"key": "64701",
						"value": "导出",
						"sortIndex": 21508,
						"parentKey": "61323",
						"isLeaf": false,
						"checkboxState": 2,
						"data": {
							"id": 64701,
							"lockVersion": 0,
							"name": "导出",
							"type": "PERMISSION",
							"parentId": 61323,
							"permission": "schedule:export",
							"sortIndex": 21508,
							"locked": false
						},
						"leaf": false
					}],
					"key": "61323",
					"value": "班次管理",
					"sortIndex": 21500,
					"parentKey": "61322",
					"isLeaf": false,
					"checkboxState": 2,
					"data": {
						"id": 61323,
						"lockVersion": 0,
						"name": "班次管理",
						"type": "MENU",
						"url": "#pjs/ScheduleInfo",
						"parentId": 61322,
						"parentPath": "61352|61316|61322|61323",
						"sortIndex": 21500,
						"locked": false
					},
					"leaf": false
				}],
				"key": "61322",
				"value": "路由配置(普通)",
				"sortIndex": 21000,
				"parentKey": "61316",
				"isLeaf": false,
				"checkboxState": 2,
				"data": {
					"id": 61322,
					"lockVersion": 0,
					"name": "路由配置(普通)",
					"type": "MENU_DIR",
					"parentId": 61316,
					"parentPath": "61352|61316",
					"sortIndex": 21000,
					"locked": false
				},
				"leaf": false
			}, {
				"children": [{
					"key": "64637",
					"value": "导入",
					"sortIndex": 23001,
					"parentKey": "61321",
					"isLeaf": false,
					"checkboxState": 2,
					"data": {
						"id": 64637,
						"lockVersion": 0,
						"name": "导入",
						"type": "PERMISSION",
						"parentId": 61321,
						"permission": "marketAging:import",
						"sortIndex": 23001,
						"locked": false
					},
					"leaf": false
				}, {
					"key": "64638",
					"value": "导入模板下载",
					"sortIndex": 23002,
					"parentKey": "61321",
					"isLeaf": false,
					"checkboxState": 2,
					"data": {
						"id": 64638,
						"lockVersion": 0,
						"name": "导入模板下载",
						"type": "PERMISSION",
						"parentId": 61321,
						"permission": "marketAging:download",
						"sortIndex": 23002,
						"locked": false
					},
					"leaf": false
				}, {
					"key": "64639",
					"value": "编辑",
					"sortIndex": 23003,
					"parentKey": "61321",
					"isLeaf": false,
					"checkboxState": 2,
					"data": {
						"id": 64639,
						"lockVersion": 0,
						"name": "编辑",
						"type": "PERMISSION",
						"parentId": 61321,
						"permission": "marketAging:edit",
						"sortIndex": 23003,
						"locked": false
					},
					"leaf": false
				}, {
					"key": "64640",
					"value": "删除",
					"sortIndex": 23004,
					"parentKey": "61321",
					"isLeaf": false,
					"checkboxState": 2,
					"data": {
						"id": 64640,
						"lockVersion": 0,
						"name": "删除",
						"type": "PERMISSION",
						"parentId": 61321,
						"permission": "marketAging:delete",
						"sortIndex": 23004,
						"locked": false
					},
					"leaf": false
				}],
				"key": "61321",
				"value": "静态时效",
				"sortIndex": 23000,
				"parentKey": "61316",
				"isLeaf": false,
				"checkboxState": 2,
				"data": {
					"id": 61321,
					"lockVersion": 0,
					"name": "静态时效",
					"type": "MENU",
					"url": "#pjs/MarketAgingInfo",
					"parentId": 61316,
					"parentPath": "61352|61316|61321",
					"sortIndex": 23000,
					"locked": false
				},
				"leaf": false
			}],
			"key": "61316",
			"value": "路由配置",
			"sortIndex": 20000,
			"parentKey": "61352",
			"isLeaf": false,
			"checkboxState": 2,
			"data": {
				"id": 61316,
				"lockVersion": 0,
				"name": "路由配置",
				"type": "MENU_DIR",
				"parentId": 61352,
				"parentPath": "61352|61316",
				"sortIndex": 20000,
				"locked": false
			},
			"leaf": false
		}, {
			"children": [{
				"children": [{
					"key": "64641",
					"value": "导出",
					"sortIndex": 31001,
					"parentKey": "61325",
					"isLeaf": false,
					"checkboxState": 2,
					"data": {
						"id": 64641,
						"lockVersion": 0,
						"name": "导出",
						"type": "PERMISSION",
						"parentId": 61325,
						"permission": "batchQueryInfo:export",
						"sortIndex": 31001,
						"locked": false
					},
					"leaf": false
				}],
				"key": "61325",
				"value": "批次信息查询",
				"sortIndex": 31000,
				"parentKey": "61317",
				"isLeaf": false,
				"checkboxState": 2,
				"data": {
					"id": 61325,
					"lockVersion": 0,
					"name": "批次信息查询",
					"type": "MENU",
					"url": "#pjs/BatchQueryInfo",
					"parentId": 61317,
					"parentPath": "61352|61317|61325",
					"sortIndex": 31000,
					"locked": false
				},
				"leaf": false
			}, {
				"children": [{
					"key": "64643",
					"value": "导出",
					"sortIndex": 32001,
					"parentKey": "61326",
					"isLeaf": false,
					"checkboxState": 2,
					"data": {
						"id": 64643,
						"lockVersion": 0,
						"name": "导出",
						"type": "PERMISSION",
						"parentId": 61326,
						"permission": "waveQueryInfo:export",
						"sortIndex": 32001,
						"locked": false
					},
					"leaf": false
				}],
				"key": "61326",
				"value": "频次信息查询",
				"sortIndex": 32000,
				"parentKey": "61317",
				"isLeaf": false,
				"checkboxState": 2,
				"data": {
					"id": 61326,
					"lockVersion": 0,
					"name": "频次信息查询",
					"type": "MENU",
					"url": "#pjs/WaveQueryInfo",
					"parentId": 61317,
					"parentPath": "61352|61317|61326",
					"sortIndex": 32000,
					"locked": false
				},
				"leaf": false
			}, {
				"key": "61310",
				"value": "分拨路由查询",
				"sortIndex": 32001,
				"parentKey": "61317",
				"isLeaf": false,
				"checkboxState": 2,
				"data": {
					"id": 61310,
					"lockVersion": 0,
					"name": "分拨路由查询",
					"type": "MENU",
					"url": "#pjs/NewRouteQueryInfo",
					"parentId": 61317,
					"parentPath": "61352|61317|61310",
					"sortIndex": 32001,
					"locked": false
				},
				"leaf": false
			}, {
				"key": "61311",
				"value": "城市静态时效查询",
				"sortIndex": 32002,
				"parentKey": "61317",
				"isLeaf": false,
				"checkboxState": 2,
				"data": {
					"id": 61311,
					"lockVersion": 0,
					"name": "城市静态时效查询",
					"type": "MENU",
					"url": "#pjs/StaticAgingQueryInfo",
					"parentId": 61317,
					"parentPath": "61352|61317|61311",
					"sortIndex": 32002,
					"locked": false
				},
				"leaf": false
			}, {
				"key": "62880",
				"value": "报表导出",
				"sortIndex": 33004,
				"parentKey": "61317",
				"isLeaf": false,
				"checkboxState": 2,
				"data": {
					"id": 62880,
					"lockVersion": 0,
					"name": "报表导出",
					"type": "MENU",
					"url": "#pjs/ReportInfo",
					"parentId": 61317,
					"parentPath": "61352|61317|62880",
					"sortIndex": 33004,
					"locked": false
				},
				"leaf": false
			}],
			"key": "61317",
			"value": "路由查询",
			"sortIndex": 30000,
			"parentKey": "61352",
			"isLeaf": false,
			"checkboxState": 2,
			"data": {
				"id": 61317,
				"lockVersion": 0,
				"name": "路由查询",
				"type": "MENU_DIR",
				"parentId": 61352,
				"parentPath": "61352|61317",
				"sortIndex": 30000,
				"locked": false
			},
			"leaf": false
		}, {
			"children": [{
				"key": "61329",
				"value": "网点签收时效表(Q9)",
				"sortIndex": 42000,
				"parentKey": "61318",
				"isLeaf": false,
				"checkboxState": 2,
				"data": {
					"id": 61329,
					"lockVersion": 0,
					"name": "网点签收时效表(Q9)",
					"type": "MENU",
					"url": "#pjs/SignScheduleInfo",
					"parentId": 61318,
					"parentPath": "61352|61318|61329",
					"sortIndex": 42000,
					"locked": false
				},
				"leaf": false
			}],
			"key": "61318",
			"value": "站点管理",
			"sortIndex": 40000,
			"parentKey": "61352",
			"isLeaf": false,
			"checkboxState": 2,
			"data": {
				"id": 61318,
				"lockVersion": 0,
				"name": "站点管理",
				"type": "MENU_DIR",
				"parentId": 61352,
				"parentPath": "61352|61318",
				"sortIndex": 40000,
				"locked": false
			},
			"leaf": false
		}],
		"key": "61352",
		"value": "菜单权限",
		"sortIndex": 0,
		"isLeaf": false,
		"checkboxState": 2,
		"data": {
			"id": 61352,
			"lockVersion": 0,
			"name": "菜单权限",
			"type": "MENU_DIR",
			"parentPath": "61352|",
			"sortIndex": 0,
			"locked": false
		},
		"leaf": false
	}
}

data
